version: "3"
services:
  db: 
    build: .
    restart: always
    environment: 
      - POSTGRES_PASSWORD:${PG_PASSWORD}
      - POSTGRES_USER:${PG_USER}
      - POSTGRES_DB:${PG_DB}
    volumes: 
      - ~/.players_api/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
